name: Build & Publish Images

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  API_IMAGE: ${{ github.repository_owner }}/smart-travel-api
  WEB_IMAGE: ${{ github.repository_owner }}/smart-travel-web

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        run: |
          docker build \
            -f smart-travel-backend/services/api/Dockerfile \
            -t $REGISTRY/$API_IMAGE:${GITHUB_SHA} \
            .

      - name: Build web image
        run: |
          docker build \
            -f smart-travel-frontend/apps/web/Dockerfile \
            -t $REGISTRY/$WEB_IMAGE:${GITHUB_SHA} \
            .

      - name: Push images
        run: |
          docker push $REGISTRY/$API_IMAGE:${GITHUB_SHA}
          docker push $REGISTRY/$WEB_IMAGE:${GITHUB_SHA}
