name: Build & Publish Images

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  OWNER_SLUG: ${{ github.repository_owner || '' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API image
        run: |
          IMAGE=${REGISTRY}/$(echo "${OWNER_SLUG}/smart-travel-api" | tr '[:upper:]' '[:lower:]')
          docker build \
            -f smart-travel-backend/services/api/Dockerfile \
            -t ${IMAGE}:${GITHUB_SHA} \
            .
          echo "API_IMAGE_TAG=${IMAGE}:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build web image
        run: |
          IMAGE=${REGISTRY}/$(echo "${OWNER_SLUG}/smart-travel-web" | tr '[:upper:]' '[:lower:]')
          docker build \
            -f smart-travel-frontend/apps/web/Dockerfile \
            -t ${IMAGE}:${GITHUB_SHA} \
            .
          echo "WEB_IMAGE_TAG=${IMAGE}:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Push images
        run: |
          docker push $API_IMAGE_TAG
          docker push $WEB_IMAGE_TAG
